### ISSUE TITLE
FormatException after attempt to drag and move plot with mouse

### ISSUE THREAD

**Issue by FonyRockfeel** [oxyplot/docs#1]
I use TimeSpanAxis type. After creating and adding plots to plotview, any attempt to drag and move the plot in Plotview gives FormatException. But zooming with rolling mousewheel works correctly and don't give any exception. If there are not any plot in Plotview, dragging and moving with mouse works correctly.

**Comment by objorke** [comment]
Please add this issue to https://github.com/oxyplot/oxyplot/issues (this is not a docs issue)
Can you also provide code that reproduces the bug in the ExampleLibrary?
