### ISSUE TITLE
WPF not displayed at run-time

### ISSUE THREAD

**Issue by jenokizm** [oxyplot/docs#22]
The graph is displayed in the designer VS, but when the program launch it is not (
video https://1drv.ms/v/s!Aq6ZQkyoPcuM-mcyemb7Q64agMzh

**Comment by objorke** [comment]
Is this one of the examples from the documentation? Otherwise, this is an issue for the oxyplot/oxyplot repository. It would also be good to have the code that reproduces the error!

**Comment by jenokizm** [comment]
yes, this example from the documentation. I could not fix it, and I do not have time to determine the cause. I just put the component instead of your other **LiveCharts.Wpf**

**Comment by objorke** [comment]
this example?
http://docs.oxyplot.org/en/latest/getting-started/hello-wpf.html

**Comment by objorke** [comment]
Cannot reproduce this.
